### ISSUE TITLE
"outging" -> "outgoing" typo in English localization file

### ISSUE THREAD

**Issue by Ropid** [spamwax/EavesDrop#12]
A tiny mistake, on line 11 in `locals/localization-enUS.lua` it should say `"Outgoing"`, it's missing an `'o'` right now:

https://github.com/spamwax/EavesDrop/blob/85bbf1b82eb2f01c7a89069b9f9ac6defd371961/locals/localization-enUS.lua#L11

**Comment by spamwax** [comment]
Thank you for your report, it will be fixed in next release during DF prepatch
