### ISSUE TITLE
Outline effect to text

### ISSUE THREAD

**Issue by Moofushi** [spamwax/EavesDrop#13]
Hello!
Since version for 10.0 i have text outlines. Is there an option to remove it?
I can not find any options in any of the tabs where you can customize the look of the addon.
![eavesdrop](https://user-images.githubusercontent.com/116982221/198854763-515cbe1e-35b6-4098-8905-90c1f398d511.png)

**Comment by spamwax** [comment]
Right now, there is no option to change the outline.
It is on my todo list though

**Comment by Moofushi** [comment]
I appreciate the work you are doing!
