### ISSUE TITLE
Question to the author

### ISSUE THREAD

**Issue by Soulmoonko** [spamwax/EavesDrop#15]
Is there an option to bring back to life an analogue of this addon [EavesDrop] - Сascade?
Or implement in your addon separate columns for the pet?
In the version for WOTLK, incoming damage is not tinted to the color of the school of magic, this is very inconvenient. Will it be implemented in the future?

**Comment by vbhayden** [comment]
Using this one rather than making another issue, how far back was this cloned from domzae's work?  I've been maintaining a branch to update for SL and now DF with a few small quality of life changes, but can't merge directly here as this isn't a fork etc.

**Comment by spamwax** [comment]
> Is there an option to bring back to life an analogue of this addon [EavesDrop] - Сascade? Or implement in your addon separate columns for the pet? In the version for WOTLK, incoming damage is not tinted to the color of the school of magic, this is very inconvenient. Will it be implemented in the future?

- Unfortunately I do not have time to work on Cascade
- What you are asking will be a big change in terms of EavesDrop's UI. Given that this addon has 16-years of history and fans I do not want to change the UI in big ways. However I welcome suggestions and PRs that would implement features in a non-intrusive way to current users
- I don't play WOTLK, so the testing is minimal  in 3.4.0. Please open a separate issue and fully explain the bug/problem with possible screenshots

**Comment by spamwax** [comment]
> Using this one rather than making another issue, how far back was this cloned from domzae's work? I've been maintaining a branch to update for SL and now DF with a few small quality of life changes, but can't merge directly here as this isn't a fork etc.

I cannot remember. Probably it's a mix of domzae's fixes and my additions.
What are the QOL changes you have in mind?

**Comment by spamwax** [comment]
@vbhayden started a (separate issue](https://github.com/spamwax/EavesDrop/issues/16) since for your question I am closing this
