### ISSUE TITLE
merging some QOL changes from another repo

### ISSUE THREAD

**Issue by spamwax** [spamwax/EavesDrop#16]
Using this one rather than making another issue, how far back was this cloned from domzae's work?  I've been maintaining a branch to update for SL and now DF with a few small quality of life changes, but can't merge directly here as this isn't a fork etc.

_Originally posted by @vbhayden in https://github.com/spamwax/EavesDrop/issues/15#issuecomment-1335504656_

**Comment by spamwax** [comment]
[From original post](https://github.com/spamwax/EavesDrop/issues/15#issuecomment-1335826408)

**Comment by vbhayden** [comment]
Oh sure, so it was mostly just cleaning up the tooltip when you hover over the log entries.  The version I worked on would show 2 timestamps and also not specify when a buff was applied -- only that something happened at that time.

Original was: https://github.com/domzae/EavesDrop/pull/5

If this version has already cleaned that up, then all good and this can be closed.  :-)

**Comment by spamwax** [comment]
Yes, this repo has that commit (and a fix to a typo in its line 726)

**Comment by vbhayden** [comment]
Oh great, np then ty.
