### ISSUE TITLE
On-death sound

### ISSUE THREAD

**Issue by cynicalsubject** [spamwax/EavesDrop#17]
I noticed that now there's a sound that fires up everytime you (or your pets) die. Is there a way to disable it? I'd normally not mind it, except it becomes incredibly annoying in pvp where a death can occur quite frequently.

For the time being I've commented out a section in `EavesDrop.lua` starting at line 825 so the event is disabled.

Using version 3.1 on retail WoW.

**Comment by spamwax** [comment]
Yes, the next release of addon will include an option. Sorry for the the annoyance caused.
