### ISSUE TITLE
WoW Wotlk 3.4.1 API Changes broke EavesDrop

### ISSUE THREAD

**Issue by schn4ppi** [spamwax/EavesDrop#18]
I encountered three EavesDrop Lua errors so far:

**Number 1**
EavesDrop/EavesDrop.lua:489: attempt to call method 'SetGradientAlpha' (a nil value)
[string "@EavesDrop/EavesDrop.lua"]:489: in function `PerformDisplayOptions'
[string "@EavesDrop/EavesDrop.lua"]:279: in function <EavesDrop/EavesDrop.lua:253>
[string "=[C]"]: ?
[string "@Details/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...ceDetails/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Details/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Details/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <...ceDetails/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

**Number 2**
[string "*EavesDrop.xml:533_OnEnter"]:3: Usage: GameTooltip:SetText("text" [, color, wrap])
[string "=[C]"]: in function `SetText'
[string "*EavesDrop.xml:533_OnEnter"]:3: in function <[string "*EavesDrop.xml:533_OnEnter"]:1>

Locals:
(*temporary) = GameTooltip {
 0 = <userdata>
 GetBackdropColor = <function> defined @SharedXML/SharedTooltipTemplates.lua:191
 SetHyperlink = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 hasMoney = 1
 SetBackdropBorderColor = <function> defined @SharedXML/SharedTooltipTemplates.lua:195
 Hide = <function> defined =[C]:-1
 SetCraftItem = <function> defined =[C]:-1
 comparing = false
 SetSocketGem = <function> defined =[C]:-1
 TopOverlay = Texture {
 }
 GetBackdropBorderColor = <function> defined @SharedXML/SharedTooltipTemplates.lua:199
 SetUnitDebuff = <function> defined =[C]:-1
 SetItemByID = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 SetBorderBlendMode = <function> defined @SharedXML/SharedTooltipTemplates.lua:203
 SetTrainerService = <function> defined =[C]:-1
 numMoneyFrames = 2
 SetInboxItem = <function> defined =[C]:-1
 layoutType = "TooltipDefaultLayout"
 shoppingTooltips = <table> {
 }
 SetExistingSocketGem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 SetTradeSkillItem = <function> defined =[C]:-1
 SetTradeTargetItem = <function> defined =[C]:-1
 SetCurrencyTokenByID = <function> defined =[C]:-1
 SetTradePlayerItem = <function> defined =[C]:-1
 SetUnitBuff = <function> defined =[C]:-1
 SetSendMailItem = <function> defined =[C]:-1
 NineSlice = Frame {
 }
 updateTooltip = 0.077000
 SetInventoryItem = <function> defined =[C]:-1
 StatusBar = GameTooltipStatusBar {
 }
 TooltipBackdropOnLoad = <function> defined @SharedXML/SharedTooltipTemplates.lua:172
 SetUnitAura = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 SetAuctionSellItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 BottomOverlay = Texture {
 }
 SetBackdropColor = <function> defined @SharedXML/SharedTooltipTemplates.lua:187
 SetLootRollItem = <function> defined =[C]:-1
 SetAuctionItem = <function> defined =[C]:-1
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = 1

**And in combat number 3**

8x EavesDrop/EavesDropStats.lua:70: attempt to index upvalue 'db' (a nil value)
[string "@EavesDrop/EavesDropStats.lua"]:70: in function `TrackStat'
[string "@EavesDrop/EavesDrop.lua"]:672: in function `?'
[string "@DBM-Core/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ore/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@DBM-Core/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ore/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@DBM-Core/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@EavesDrop/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <EavesDrop/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = <table> {
 TrackStat = <function> defined @EavesDrop/EavesDropStats.lua:68
 SetDefaultModuleLibraries = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 IsRetail = <function> defined @EavesDrop/EavesDrop.lua:206
 ScrollUp = <function> defined @EavesDrop/EavesDrop.lua:1320
 EnableModule = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 CancelTimer = <function> defined @Details/Libs/AceTimer-3.0/AceTimer-3.0.lua:147
 IterateEmbeds = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:438
 SetupHistory = <function> defined @EavesDrop/EavesDropStats.lua:161
 UpdateRepHonorEvents = <function> defined @EavesDrop/EavesDrop.lua:408
 ResetEvents = <function> defined @EavesDrop/EavesDrop.lua:1204
 Printf = <function> defined @EavesDrop/libs/AceConsole-3.0/AceConsole-3.0.lua:65
 ScrollToBottom = <function> defined @EavesDrop/EavesDrop.lua:1314
 SetDefaultModulePrototype = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:405
 defaultModuleState = true
 IsEnabled = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:447
 ScheduleTimer = <function> defined @Details/Libs/AceTimer-3.0/AceTimer-3.0.lua:94
 DisableModule = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:346
 RegisterMessage = <function> defined @DBM-Core/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 GetArgs = <function> defined @EavesDrop/libs/AceConsole-3.0/AceConsole-3.0.lua:140
 ShowHistory = <function> defined @EavesDrop/EavesDrop.lua:1431
 blacklist = <table> {
 }
 SetFonts = <function> defined @EavesDrop/EavesDrop.lua:540
 CombatEvent = <function> defined @EavesDrop/EavesDrop.lua:565
 ShortenString = <function> defined @EavesDrop/EavesDrop.lua:1402
 SetEnabledState = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 ShowFrame = <function> defined @EavesDrop/EavesDrop.lua:559
 enabledState = true
 RegisterEvent = <function> defined @DBM-Core/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 SendToChat = <function> defined @EavesDrop/EavesDrop.lua:1417
 IterateModules = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:433
 ScrollDown = <function> defined @EavesDrop/EavesDrop.lua:1327
 UpdateExpEvents = <function> defined @EavesDrop/EavesDrop.lua:400
 options = <table> {
 }
 chardb = <table> {
 }
 shortenValue = <function> defined @EavesDrop/EavesDrop.lua:212
 SetDisplay = <function> defined @EavesDrop/EavesDropStats.lua:56
 showPrints = true
 db = <table> {
 }
 baseName = "EavesDrop"
 OnInitialize = <function> defined @EavesDrop/EavesDrop.lua:253
 NewModule = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:231
 OpenMenu = <function> defined @EavesDrop/options.lua:928
 OnUpdate = <function> defined @EavesDrop/EavesDrop.lua:1226
 SetupOptions = <function> defined @EavesDrop/options.lua:166
 GetModule = <function> defined @Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:206
 PLAYER_DEAD = <function> defined @EavesDrop/EavesDrop.lua:1047
 IsClassic = <function> defined @EavesDrop/EavesDrop.lua:201
 PlaceHistoryFrame = <function> defined @EavesDrop/EavesDropStats.lua:213
 UpdateCombatEvents = <function> defined @EavesDrop/EavesDrop.lua:390
 TimeLeft = <function> defined @Details/Libs/AceTimer-3.0/AceTimer-3.0.lua:172
 FindCombatDown = <function> defined @EavesDrop/EavesDrop.lua:1297
 U

**Comment by spamwax** [comment]
Thanks for the report, I will push a fix, but try using the Retail version for now, it may work!
