### ISSUE TITLE
Any way to manually change spell icons?

### ISSUE THREAD

**Issue by Ayzkronos** [spamwax/EavesDrop#2]
https://i.gyazo.com/4debb7b2db28c857e06d4949ab4e1c5e.png
Multiple basic spells such as Restore Mana and many many others dont have an appropriate icon.
While using this addon throughout vanilla classic, a friend of mine changed some of the code which allowed me and him to manually look up the spell ids, and find matching spell icons to those spells. This is what he did

 **-- Oron edit
local spellNameId = {
    [GetSpellInfo(11903)] = {texture = GetItemIcon(33093)}, -- Greater Mana Potion** 

and then under the various "damage" "buffs" categories, he had added 

if spellNameId[spellName] then 
	    texture = spellNameId[spellName].texture
	else
	    texture = GetSpellTexture(spellName)
end

This worked for us, and allowed us to take it upon ourselves to go through all of the warcraftlogs, and find spell IDs on every attack, buff and debuff that were likely to be afflicted upon a player. 

I have tried to re-write the code myself in your version (which i downloaded today), but im an addon noob and all i could do was to try and copy the method he used in the vanilla classic version. My initial test worked great - i was able to manually add a mana potion icon for the greater mana potion as the example i tested out. But upon some relogging, now when i log in the whole eavesdrop box is completely white/blank, so i suspect i broken something.

All the best, thanks for working on this amazing addon
/ayzofc

**Comment by spamwax** [comment]
Thanks for reporting.
I think we need to first figure out why some spells don't have an icon.
The hack/trick you mentioned is very fragile and as you mentioned tedious. 
What are very common spells/casts that you don't see icon for?

**Comment by spamwax** [comment]
I should also mention that I am not a "pro" addon developer and my goal with this project is to make it work with least amount of time investment :)

**Comment by Ayzkronos** [comment]
It's not that there is no icon, it is that blizzard haven't bothered giving the ability an icon which gives some hint to what the ability/action is; it's just the face of a guy as an icon, most commonly seen when interacting with an object like opening a chest. So every time you use an ability like this, or get struck by an attack or debuff which has this icon, it shows up on eavesdrop with that icon. It just don't give you the information you're looking for as you glance over the addon and ask yourself "what hit me?" 

I'll check through my vod of my upcoming raid tonight, and see which effects dont show great in eavesdrop and bring back a hopefully short list for you :)

**Comment by Ayzkronos** [comment]
https://i.gyazo.com/4ba1390c3bc7129262d29ebd8dd082f4.png
Weapon Oils, Healing Potions and Mana Potions were the only ones that had blank or "face" icon throughout my raid of SSC and TK tonight.

**Comment by spamwax** [comment]
closing the issue due to long inactivity
