### ISSUE TITLE
3.4.0 Classic WOW

### ISSUE THREAD

**Issue by Kixum** [spamwax/EavesDrop#6]
Hello, I was wondering if it's possible to fix the latest WOTLK version of eavesdrop to make it work on the current 3.4.0 WOTLK Classic? I have used this addon for 15 years and I miss it sorely, there seems to be no reason why it shouldn't work on 3.4.0 since it worked perfectly on 3.3.5a, but alas.

**Comment by spamwax** [comment]
No promises, but I will try to get it going. 
If you are using any bug-catcher in 3.4.0, can you share any errors you are getting?

**Comment by spamwax** [comment]
I just tested this on 3.4.0, and it was working just fine.
Please reopen the issue with specific errors/problems you are experiencing.

**Comment by Kixum** [comment]
No errors this one just doesn't appear in the addons list at all. The other ones I've tried load normally but the GUI is stuck in the middle of screen, unresposnive and it doesn't track anything.

**Comment by Kixum** [comment]
My god I didnt clear the savedvariables before testing this one, it works. I am sorry for wasting your time :D. Thanks for the work.
